---
- name: "Equilibrage des charges"
  hosts: ansible_local
  ignore_errors: yes
  become: yes

  vars:
    haproxy_backend_servers:
      - name: formation
        address: 192.168.1.4:8080
      - name: Node_projet_ansible
        address: 192.168.1.51:8080

  roles:
    - { role: haproxy, when: inventory_hostname == "ansible_local" }



