---
- name: "Change target of projet grup"
  hosts:
    - projet
  become: yes
  gather_facts: yes

  tasks:
    - name: "Create symbolik link"
      file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link


