---
- name: "Creation des fichiers types selon les groupes des machines"
  hosts: all

  tasks:
    - name: "Creation du fichier type.txt  dans /etc de chaque machine"
      lineinfile:
        path: /etc/type.txt 
        create: yes
        line: "{%if inventory_hostname in groups['projet']%}developpement{%else%}test{%endif%}"
      
      

  
